- id: detekt
  name: Detekt
  description: 'Runs `detekt` on modified .kt/.kts files.'
  language: script
  entry: 'entrypoint.sh host 1.22.0'
  files: \.(kt|kts)$
- id: detekt-docker
  name: Detekt
  description: 'Runs `detekt` on modified .kt/.kts files in a Docker container.'
  language: docker
  entry: '/opt/detekt/entrypoint.sh container'
  files: \.(kt|kts)$
